Konmari

diff --git a/scripts/rofi_apps/rofi_emoji b/scripts/rofi_apps/rofi_emoji
--- a/scripts/rofi_apps/rofi_emoji
+++ b/scripts/rofi_apps/rofi_emoji
@@ -2,16 +2,18 @@
 
 #〖愛〗emoji-rofi - select emoji and copy to clipboard
 
-xsel --version 2>/dev/null || exit 1
+# Housekeep
+err() { 
+	printf "Error: xsel command not found. Please install xsel.\n" 
+}
+xsel --version &>/dev/null || err && exit 1
 
-chosen=$(cut -d ';' -f1 ~/.local/share/emoji_rofi/emoji | rofi -dmenu -i -p emoji | sed "s/ .*//")
+# Get emojis
+chosen=`cut -d ';' -f1 ~/.local/share/emoji_rofi/emoji | \
+	rofi -dmenu -i -p emoji | \
+	sed "s/ .*//"
+`
+[ "$chosen" == "" ] && exit
 
-[ "$chosen" != "" ] || exit
-
-# If you run this command with an argument, it will automatically insert the character.
-if [ -n "$1" ]; then
-	xdotool key Shift+Insert
-else
-	echo "$chosen" | tr -d '\n' | xsel --clipboard
-	notify-send "'$chosen' copied to clipboard." &
-fi
+echo "$chosen" | tr -d '\n' | xsel --clipboard
+notify-send "emoji" "'$chosen' copied to clipboard."
